// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: stats.proto

package statsgrpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExperimentResultRequest identifies which experiment to compute results for.
type ExperimentResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExperimentId  string                 `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g. "conversion"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentResultRequest) Reset() {
	*x = ExperimentResultRequest{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentResultRequest) ProtoMessage() {}

func (x *ExperimentResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentResultRequest.ProtoReflect.Descriptor instead.
func (*ExperimentResultRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *ExperimentResultRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *ExperimentResultRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

// VariantResult holds the stats for one variant.
type VariantResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	NUsers        int64                  `protobuf:"varint,2,opt,name=n_users,json=nUsers,proto3" json:"n_users,omitempty"`     // number of users exposed
	NEvents       int64                  `protobuf:"varint,3,opt,name=n_events,json=nEvents,proto3" json:"n_events,omitempty"`  // number of conversions
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`                      // conversion rate (n_events / n_users)
	CiLower       float64                `protobuf:"fixed64,5,opt,name=ci_lower,json=ciLower,proto3" json:"ci_lower,omitempty"` // 95% confidence interval lower bound
	CiUpper       float64                `protobuf:"fixed64,6,opt,name=ci_upper,json=ciUpper,proto3" json:"ci_upper,omitempty"` // 95% confidence interval upper bound
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantResult) Reset() {
	*x = VariantResult{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantResult) ProtoMessage() {}

func (x *VariantResult) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantResult.ProtoReflect.Descriptor instead.
func (*VariantResult) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *VariantResult) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *VariantResult) GetNUsers() int64 {
	if x != nil {
		return x.NUsers
	}
	return 0
}

func (x *VariantResult) GetNEvents() int64 {
	if x != nil {
		return x.NEvents
	}
	return 0
}

func (x *VariantResult) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *VariantResult) GetCiLower() float64 {
	if x != nil {
		return x.CiLower
	}
	return 0
}

func (x *VariantResult) GetCiUpper() float64 {
	if x != nil {
		return x.CiUpper
	}
	return 0
}

// ExperimentResultResponse contains the full statistical result.
type ExperimentResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExperimentId  string                 `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Variants      []*VariantResult       `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	PValue        float64                `protobuf:"fixed64,4,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`                     // two-sided p-value for control vs treatment
	IsSignificant bool                   `protobuf:"varint,5,opt,name=is_significant,json=isSignificant,proto3" json:"is_significant,omitempty"` // true if p_value < 0.05
	ControlId     string                 `protobuf:"bytes,6,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`              // which variant is the control
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentResultResponse) Reset() {
	*x = ExperimentResultResponse{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentResultResponse) ProtoMessage() {}

func (x *ExperimentResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentResultResponse.ProtoReflect.Descriptor instead.
func (*ExperimentResultResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *ExperimentResultResponse) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *ExperimentResultResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ExperimentResultResponse) GetVariants() []*VariantResult {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ExperimentResultResponse) GetPValue() float64 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *ExperimentResultResponse) GetIsSignificant() bool {
	if x != nil {
		return x.IsSignificant
	}
	return false
}

func (x *ExperimentResultResponse) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x05stats\"]\n" +
	"\x17ExperimentResultRequest\x12#\n" +
	"\rexperiment_id\x18\x01 \x01(\tR\fexperimentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\"\xac\x01\n" +
	"\rVariantResult\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\tR\tvariantId\x12\x17\n" +
	"\an_users\x18\x02 \x01(\x03R\x06nUsers\x12\x19\n" +
	"\bn_events\x18\x03 \x01(\x03R\anEvents\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\x12\x19\n" +
	"\bci_lower\x18\x05 \x01(\x01R\aciLower\x12\x19\n" +
	"\bci_upper\x18\x06 \x01(\x01R\aciUpper\"\xef\x01\n" +
	"\x18ExperimentResultResponse\x12#\n" +
	"\rexperiment_id\x18\x01 \x01(\tR\fexperimentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x120\n" +
	"\bvariants\x18\x03 \x03(\v2\x14.stats.VariantResultR\bvariants\x12\x17\n" +
	"\ap_value\x18\x04 \x01(\x01R\x06pValue\x12%\n" +
	"\x0eis_significant\x18\x05 \x01(\bR\risSignificant\x12\x1d\n" +
	"\n" +
	"control_id\x18\x06 \x01(\tR\tcontrolId2f\n" +
	"\fStatsService\x12V\n" +
	"\x13GetExperimentResult\x12\x1e.stats.ExperimentResultRequest\x1a\x1f.stats.ExperimentResultResponseB(Z&github.com/Alpin-A/prism/pkg/statsgrpcb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stats_proto_goTypes = []any{
	(*ExperimentResultRequest)(nil),  // 0: stats.ExperimentResultRequest
	(*VariantResult)(nil),            // 1: stats.VariantResult
	(*ExperimentResultResponse)(nil), // 2: stats.ExperimentResultResponse
}
var file_stats_proto_depIdxs = []int32{
	1, // 0: stats.ExperimentResultResponse.variants:type_name -> stats.VariantResult
	0, // 1: stats.StatsService.GetExperimentResult:input_type -> stats.ExperimentResultRequest
	2, // 2: stats.StatsService.GetExperimentResult:output_type -> stats.ExperimentResultResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
