apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:${PROMETHEUS_INTERNAL_PORT}
    isDefault: true

  - name: Postgres
    type: postgres
    url: postgres:${POSTGRES_INTERNAL_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable