# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\"D\n\x17\x45xperimentResultRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\"x\n\rVariantResult\x12\x12\n\nvariant_id\x18\x01 \x01(\t\x12\x0f\n\x07n_users\x18\x02 \x01(\x03\x12\x10\n\x08n_events\x18\x03 \x01(\x03\x12\x0c\n\x04rate\x18\x04 \x01(\x01\x12\x10\n\x08\x63i_lower\x18\x05 \x01(\x01\x12\x10\n\x08\x63i_upper\x18\x06 \x01(\x01\"\xaa\x01\n\x18\x45xperimentResultResponse\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12&\n\x08variants\x18\x03 \x03(\x0b\x32\x14.stats.VariantResult\x12\x0f\n\x07p_value\x18\x04 \x01(\x01\x12\x16\n\x0eis_significant\x18\x05 \x01(\x08\x12\x12\n\ncontrol_id\x18\x06 \x01(\t2f\n\x0cStatsService\x12V\n\x13GetExperimentResult\x12\x1e.stats.ExperimentResultRequest\x1a\x1f.stats.ExperimentResultResponseB(Z&github.com/Alpin-A/prism/pkg/statsgrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/Alpin-A/prism/pkg/statsgrpc'
  _globals['_EXPERIMENTRESULTREQUEST']._serialized_start=22
  _globals['_EXPERIMENTRESULTREQUEST']._serialized_end=90
  _globals['_VARIANTRESULT']._serialized_start=92
  _globals['_VARIANTRESULT']._serialized_end=212
  _globals['_EXPERIMENTRESULTRESPONSE']._serialized_start=215
  _globals['_EXPERIMENTRESULTRESPONSE']._serialized_end=385
  _globals['_STATSSERVICE']._serialized_start=387
  _globals['_STATSSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
